### ISSUE TITLE
Error requiring in NodeJS

### ISSUE THREAD

**Issue by blissdev** [AndersDJohnson/fetch-paginate#4]
I tried to use this in node (v10.16.0) and get a babel error. Am I doing something wrong?

```js
const fetch = require('node-fetch');
const fetchPaginate = require('fetch-paginate');
```

and the error:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '@babel/runtime/regenerator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:958)
    at t (/Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:124)
    at Module.<anonymous> (/Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:1307)
    at t (/Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:124)
    at /Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:923
    at Object.<anonymous> (/Users/me/projects/lh-stats/node_modules/fetch-paginate/dist/main.js:1:932)
```

**Comment by AndersDJohnson** [comment]
@blissdev Hey, thanks for reporting! Somehow `@babel/runtime` ended up in the `devDependencies` here instead of `dependencies`. I've switched it and published as `3.2.1`, can you give that new version a shot and report back whether it works?

**Comment by blissdev** [comment]
This seems to have fix it for me, thanks!

**Comment by AndersDJohnson** [comment]
@blissdev Perfect! Thanks for reporting back. Hope this package is useful to you. Please let me know you if you run into any other issues or have any ideas on how to improve it!
